#!/usr/bin/env bash
# ============================================================================
# FieldCRM — Capacitor per-tenant build script (Phase 5)
#
# Produces 2 apps per tenant: 1 iOS + 1 Android, both branded from the tenant's
# name, slug, theme, and logo. The result of each run is a `dist/tenants/<slug>`
# directory ready to be opened in Xcode / Android Studio.
#
# The script is idempotent — running it again for the same slug refreshes the
# generated `capacitor.config.ts`, icon assets, and Firebase config drop-ins.
#
# Usage:
#     ./capacitor-build.sh <tenant-slug> [ios|android|both]
#
# Prerequisites:
#     * yarn build must have produced /app/frontend/build (this script auto-builds).
#     * FCM shard credentials (Phase 5) for the tenant's shard exposed as:
#           FCM_SHARD_<i>_ANDROID_GOOGLE_SERVICES_JSON=<path>
#           FCM_SHARD_<i>_IOS_GOOGLESERVICE_INFO_PLIST=<path>
#       (Optional — build still succeeds, but push won't work on that shard.)
#     * BACKEND_URL and ROOT_DOMAIN set in env — used to fetch tenant metadata
#       and to derive Capacitor server URL.
# ============================================================================

set -euo pipefail

SLUG="${1:-}"
TARGET="${2:-both}"
if [[ -z "$SLUG" ]]; then
    echo "Usage: $0 <tenant-slug> [ios|android|both]" >&2
    exit 2
fi

: "${BACKEND_URL:?Set BACKEND_URL, e.g. https://api.fieldcrm.app}"

FRONTEND_DIR="${FRONTEND_DIR:-/app/frontend}"
OUT_DIR="${OUT_DIR:-/app/dist/tenants/$SLUG}"

echo "==> [1/6] Fetching tenant '$SLUG' metadata from $BACKEND_URL"
TENANT_JSON=$(curl -sf "$BACKEND_URL/api/public/tenants/by-slug/$SLUG") || {
    echo "ERROR: could not fetch tenant $SLUG" >&2; exit 1;
}

# --- Extract fields (jq required) ---
command -v jq >/dev/null || { echo "ERROR: jq is required (apt-get install jq)"; exit 1; }
NAME=$(echo "$TENANT_JSON"   | jq -r '.name // empty')
TENANT_ID=$(echo "$TENANT_JSON" | jq -r '.id')
LANG=$(echo "$TENANT_JSON"   | jq -r '.default_language // "en"')
PRIMARY=$(echo "$TENANT_JSON" | jq -r '.theme.primary // "#2C5E43"')

# Sanitise slug into a reverse-DNS app id: only [a-z0-9]
CLEAN_SLUG=$(echo "$SLUG" | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9')
APP_ID="in.localappstore.fieldcrm.${CLEAN_SLUG}"
APP_NAME="${NAME:-FieldCRM $SLUG}"

echo "    Name     : $APP_NAME"
echo "    App ID   : $APP_ID"
echo "    Language : $LANG"
echo "    Primary  : $PRIMARY"

# --- Prepare output dir + copy the freshly-built React app ---
echo "==> [2/6] Building web bundle"
cd "$FRONTEND_DIR"
if [[ ! -d build ]] || [[ "${FORCE_REBUILD:-0}" == "1" ]]; then
    yarn build
fi

mkdir -p "$OUT_DIR"
cp -R build "$OUT_DIR/webapp"

# --- Emit tenant-branded capacitor.config.ts ---
echo "==> [3/6] Writing capacitor.config.ts"
cat > "$OUT_DIR/capacitor.config.ts" <<EOF
// GENERATED by capacitor-build.sh for tenant "$SLUG" ($TENANT_ID)
// Do not edit by hand — re-run capacitor-build.sh to refresh.
import type { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: '$APP_ID',
  appName: '$APP_NAME',
  webDir: 'webapp',
  server: {
    // Deep-linkable HTTPS host. When ROOT_DOMAIN is set, the app can also be
    // packaged as an offline shell that falls back to \${SLUG}.\${ROOT_DOMAIN}.
    androidScheme: 'https',
    hostname: '${ROOT_DOMAIN:+$SLUG.$ROOT_DOMAIN}',
    iosScheme: 'https',
  },
  ios: {
    contentInset: 'always',
    limitsNavigationsToAppBoundDomains: true,
  },
  android: {
    allowMixedContent: false,
    captureInput: true,
  },
  plugins: {
    SplashScreen: { launchAutoHide: true, backgroundColor: '$PRIMARY' },
    PushNotifications: { presentationOptions: ['badge', 'sound', 'alert'] },
  },
};
export default config;
EOF

# --- Save tenant metadata JSON alongside for CI / debugging ---
echo "$TENANT_JSON" > "$OUT_DIR/tenant.json"

# --- Fetch and place logo as an app icon (best effort) ---
echo "==> [4/6] Fetching logo"
LOGO_PATH=$(echo "$TENANT_JSON" | jq -r '.logo_path // empty')
if [[ -n "$LOGO_PATH" ]]; then
    curl -sf -o "$OUT_DIR/icon.raw" \
        "$BACKEND_URL/api/files/view?path=$LOGO_PATH" || true
fi
if [[ ! -s "$OUT_DIR/icon.raw" ]]; then
    cp "$FRONTEND_DIR/public/favicon.ico" "$OUT_DIR/icon.raw" 2>/dev/null || true
fi

# --- Drop Firebase config for the tenant's shard, if provided ---
echo "==> [5/6] Wiring FCM config (shard-aware)"
SHARD_ID=$(curl -sf -H "X-Tenant-Slug: $SLUG" "$BACKEND_URL/api/admin/push/status" 2>/dev/null | jq -r '.shard_id // 1' || echo 1)
ANDROID_CONF_VAR="FCM_SHARD_${SHARD_ID}_ANDROID_GOOGLE_SERVICES_JSON"
IOS_CONF_VAR="FCM_SHARD_${SHARD_ID}_IOS_GOOGLESERVICE_INFO_PLIST"
if [[ -n "${!ANDROID_CONF_VAR:-}" && -f "${!ANDROID_CONF_VAR}" ]]; then
    cp "${!ANDROID_CONF_VAR}" "$OUT_DIR/google-services.json"
    echo "    Copied google-services.json (shard $SHARD_ID)"
else
    echo "    (Optional) $ANDROID_CONF_VAR not set — Android push disabled"
fi
if [[ -n "${!IOS_CONF_VAR:-}" && -f "${!IOS_CONF_VAR}" ]]; then
    cp "${!IOS_CONF_VAR}" "$OUT_DIR/GoogleService-Info.plist"
    echo "    Copied GoogleService-Info.plist (shard $SHARD_ID)"
else
    echo "    (Optional) $IOS_CONF_VAR not set — iOS push disabled"
fi

# --- Run Capacitor add + sync in the output directory ---
echo "==> [6/6] Running capacitor sync"
cd "$OUT_DIR"
# Minimal package.json so `cap` can bootstrap.
cat > package.json <<EOF
{
  "name": "fieldcrm-$CLEAN_SLUG",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "@capacitor/core": "^7.0.0",
    "@capacitor/ios": "^7.0.0",
    "@capacitor/android": "^7.0.0",
    "@capacitor/splash-screen": "^7.0.0",
    "@capacitor/push-notifications": "^7.0.0"
  },
  "devDependencies": {
    "@capacitor/cli": "^7.0.0"
  }
}
EOF

if [[ ! -d node_modules ]]; then
    yarn install --frozen-lockfile 2>/dev/null || yarn install
fi

case "$TARGET" in
    ios)     yarn cap add ios     2>/dev/null || true; yarn cap sync ios ;;
    android) yarn cap add android 2>/dev/null || true; yarn cap sync android ;;
    both|*)  yarn cap add ios 2>/dev/null || true
             yarn cap add android 2>/dev/null || true
             yarn cap sync ;;
esac

echo ""
echo "✅  Tenant '$SLUG' Capacitor bundle ready at:"
echo "    $OUT_DIR"
echo ""
echo "Next steps:"
echo "  iOS     : yarn cap open ios         # (macOS + Xcode)"
echo "  Android : yarn cap open android     # (Android Studio)"
