"""Capacitor project bootstrap.

Responsibilities:
  * mkdir the per-tenant output directory
  * copy the pre-built React web bundle (`/app/frontend/build`) into `webapp/`
  * write a tenant-branded `capacitor.config.ts`
  * write a minimal `package.json` with pinned Capacitor deps
  * write `tenant.json` for debugging + reproducibility
  * `yarn install`
  * `npx cap add android|ios` (idempotent — swallows "already added" errors)
  * `npx cap sync <platform>` after android.py / ios.py apply their branding
"""
from __future__ import annotations

import json
import os
import shutil
from pathlib import Path
from typing import Optional

from .manifest import BuildManifest
from .utils import ensure_dir, has_command, log, run, write_text


# Pinned Capacitor major version — matches capacitor-build.sh
CAP_VERSION = "^7.0.0"

PACKAGE_JSON_TMPL = {
    "name": "",  # filled in per tenant
    "version": "1.0.0",
    "private": True,
    "dependencies": {
        "@capacitor/core": CAP_VERSION,
        "@capacitor/ios": CAP_VERSION,
        "@capacitor/android": CAP_VERSION,
        "@capacitor/splash-screen": CAP_VERSION,
        "@capacitor/push-notifications": CAP_VERSION,
        "@capacitor/status-bar": CAP_VERSION,
        "@capacitor/keyboard": CAP_VERSION,
    },
    "devDependencies": {
        "@capacitor/cli": CAP_VERSION,
        "typescript": "^5.4.0",
    },
}


def out_dir_for(slug: str, base: Optional[Path] = None) -> Path:
    base = base or Path(os.environ.get("BUILD_OUT_ROOT", "/app/dist/tenants"))
    return base / slug


def copy_web_bundle(frontend_dir: Path, target: Path,
                    force_rebuild: bool = False) -> None:
    build_dir = frontend_dir / "build"
    if force_rebuild or not build_dir.exists():
        log.info("Building React bundle (yarn build)")
        run(["yarn", "build"], cwd=frontend_dir)
    if not build_dir.exists():
        raise RuntimeError(f"React build failed — {build_dir} still missing")

    if target.exists():
        shutil.rmtree(target)
    shutil.copytree(build_dir, target)
    log.info(f"Copied React bundle → {target}")


def write_capacitor_config(project_root: Path, m: BuildManifest,
                           bundle_id: str, app_name: str,
                           server_url: Optional[str] = None) -> None:
    """Emit capacitor.config.ts. `server_url` overrides the on-boot host."""
    theme = m.tenant.get("theme") or {}
    primary = theme.get("primary") or "#2C5E43"

    # Deliberately NOT setting server.url — the app is fully offline-capable and
    # ships the web bundle. The `hostname` param remains for App Links / OAuth
    # continuity so that `<slug>.<ROOT_DOMAIN>` returns to the app.
    hostname = server_url.replace("https://", "").replace("http://", "") if server_url else ""
    hostname_line = f"\n    hostname: '{hostname}'," if hostname else ""

    ts = f"""// GENERATED by build_app.py for tenant "{m.slug}" ({m.tenant['id']})
// Do not edit by hand — re-run build_app.py to refresh.
import {{ CapacitorConfig }} from '@capacitor/cli';

const config: CapacitorConfig = {{
  appId: '{bundle_id}',
  appName: {json.dumps(app_name)},
  webDir: 'webapp',
  bundledWebRuntime: false,
  server: {{
    androidScheme: 'https',
    iosScheme: 'https',{hostname_line}
  }},
  ios: {{
    contentInset: 'always',
    limitsNavigationsToAppBoundDomains: false,
    backgroundColor: '{primary}',
    scheme: 'App',
  }},
  android: {{
    allowMixedContent: false,
    captureInput: true,
    backgroundColor: '{primary}',
    webContentsDebuggingEnabled: false,
  }},
  plugins: {{
    SplashScreen: {{
      launchShowDuration: 1500,
      launchAutoHide: true,
      backgroundColor: '{primary}',
      androidSplashResourceName: 'splash',
      androidScaleType: 'CENTER_CROP',
      showSpinner: false,
      splashFullScreen: true,
      splashImmersive: true,
    }},
    PushNotifications: {{
      presentationOptions: ['badge', 'sound', 'alert'],
    }},
    StatusBar: {{
      style: 'DEFAULT',
      backgroundColor: '{primary}',
      overlaysWebView: false,
    }},
    Keyboard: {{
      resize: 'body',
      style: 'DEFAULT',
      resizeOnFullScreen: true,
    }},
  }},
}};
export default config;
"""
    write_text(project_root / "capacitor.config.ts", ts)


def write_package_json(project_root: Path, slug: str) -> None:
    pkg = json.loads(json.dumps(PACKAGE_JSON_TMPL))  # deep copy
    pkg["name"] = f"fieldcrm-{slug}"
    write_text(project_root / "package.json", json.dumps(pkg, indent=2))


def install_and_bootstrap(project_root: Path, platform: str) -> None:
    """Run yarn install + capacitor `add` for the requested platform.

    `platform` must be 'android' or 'ios'. iOS `cap add` requires cocoapods,
    which is macOS-only; we still create the directory structure and let the
    user finish on their Mac.
    """
    if not has_command("yarn"):
        raise RuntimeError("yarn is required (apt-get install yarn / npm i -g yarn)")

    log.info("Installing Capacitor deps (yarn install)")
    run(["yarn", "install", "--non-interactive"], cwd=project_root)

    npx = shutil.which("npx")
    if not npx:
        raise RuntimeError("npx not found")

    # cap add is idempotent — if the folder exists Capacitor errors; we swallow it.
    log.info(f"Bootstrapping platform: {platform}")
    add_res = run([npx, "cap", "add", platform],
                  cwd=project_root, check=False, capture=True)
    if add_res.returncode != 0 and "already exists" not in (add_res.stderr or "") + (add_res.stdout or ""):
        # Not fatal for iOS — cocoapods may be missing on Linux. Log & continue.
        log.warning(f"cap add {platform} exit {add_res.returncode}")
        for line in ((add_res.stderr or "") + (add_res.stdout or "")).splitlines():
            if line.strip():
                log.warning(f"  {line}")


# end of module
